---
- name: Deploy teamcity
  hosts: teamcity
  vars_files:
    - ["vars/main.yml"]
  tasks:
    - name: run teamcity via docker
      docker:
        name: teamcity-production
        image: paralect/teamcity:9.1.6
        state: started
        restart_policy: always
        restart_policy_retry: 1000
        ports:
          - "8111:8111"
        volumes:
          - /teamcity/production:/root

    - name: run teamcity agent via docker
      docker:
        name: teamcity-agent
        privileged: true
        pull: always
        image: paralect/teamcity-agent:latest
        state: reloaded
        restart_policy: always
        restart_policy_retry: 1000
        ports:
          - "9090:9090"
        volumes:
          - /volumes/docker:/var/lib/docker
          - /volumes/data:/data
        env:
          TEAMCITY_SERVER: "{{teamcity_host}}"
          TEAMCITY_AGENT_NAME: "AgentOne"
